lab30:
	@clear
	@echo "--| Compile and Running lab_30 cpp |--"
	g++ 30/lab30.cpp -o main && ./main
	@echo "--| Running lab_30 python |--"
	python3 30/lab30.py

lab31:
	@clear
	@echo "--| Compile and Running lab_31 cpp |--"
	g++ 31/lab31.cpp -o main && ./main
	@echo "--| Running lab_31 python |--"
	python3 31/lab31.py

lab32:
	@clear
	@echo "--| Compile and Running lab_32 cpp |--"
	g++ 32/lab32.cpp -o main && ./main
	@echo "--| Running lab_32 python |--"
	python3 32/lab32.py

lab33:
	@clear
	@echo "--| Compile and Running lab_33 cpp |--"
	g++ 33/lab33.cpp -o main && ./main
	@echo "--| Running lab_33 python |--"
	python3 33/lab33.py

lab34:
	@clear
	@echo "--| Compile and Running lab_34 cpp |--"
	g++ 34/lab34.cpp -o main && ./main
	@echo "--| Running lab_34 python |--"
	python3 34/lab34.py

lab35:
	@clear
	@echo "--| Compile and Running lab_35 cpp |--"
	g++ 35/lab35.cpp -o main && ./main
	@echo "--| Running lab_35 python |--"
	python3 35/lab35.py

lab36:
	@clear
	@echo "--| Compile and Running lab_36 cpp |--"
	g++ 36/lab36.cpp -o main && ./main
	@echo "--| Running lab_36 python |--"
	python3 36/lab36.py