test1 :
	@clear
	@echo "==========C++=========="
	g++ test_1.cpp -o main && ./main
	@echo "==========C++=========="
	g++ test_1.cpp -o main && ./main
	@echo "==========Python========="
	python3 test_1.py
	@echo "==========Python========="
	python3 test_1.py
test2 :
	@clear
	@echo "==========C++=========="
	g++ test_2.cpp -o main && ./main
	@echo "==========Python=========="
	python3 test_2.py
test3 :
	@clear
	@echo "==========C++=========="
	g++ test_3.cpp -o main && ./main
	# @echo "==========Python=========="
	# python3 test_3.py